"""empty message

Revision ID: 2046aaff5bea
Revises: e9e956731bcc
Create Date: 2020-03-16 14:40:24.642670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2046aaff5bea'
down_revision = 'e9e956731bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('joindate', sa.DateTime(), nullable=True))
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('user_profiles', 'joindate')
    # ### end Alembic commands ###
