"""empty message

Revision ID: b6f5481be492
Revises: 0ed0ea9e1bcf
Create Date: 2020-05-19 00:30:44.069137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f5481be492'
down_revision = '0ed0ea9e1bcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'user_id')
    # ### end Alembic commands ###
